/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_stokesautomation_gpio_rpi_RPiGpio */

#ifndef _Included_com_stokesautomation_gpio_rpi_RPiGpio
#define _Included_com_stokesautomation_gpio_rpi_RPiGpio
#ifdef __cplusplus
extern "C" {
#endif
#undef com_stokesautomation_gpio_rpi_RPiGpio_VERSION
#define com_stokesautomation_gpio_rpi_RPiGpio_VERSION 1L
#undef com_stokesautomation_gpio_rpi_RPiGpio_INPUT
#define com_stokesautomation_gpio_rpi_RPiGpio_INPUT 1L
#undef com_stokesautomation_gpio_rpi_RPiGpio_OUTPUT
#define com_stokesautomation_gpio_rpi_RPiGpio_OUTPUT 0L
#undef com_stokesautomation_gpio_rpi_RPiGpio_ALT0
#define com_stokesautomation_gpio_rpi_RPiGpio_ALT0 4L
#undef com_stokesautomation_gpio_rpi_RPiGpio_PUD_OFF
#define com_stokesautomation_gpio_rpi_RPiGpio_PUD_OFF 0L
#undef com_stokesautomation_gpio_rpi_RPiGpio_PUD_DOWN
#define com_stokesautomation_gpio_rpi_RPiGpio_PUD_DOWN 1L
#undef com_stokesautomation_gpio_rpi_RPiGpio_PUD_UP
#define com_stokesautomation_gpio_rpi_RPiGpio_PUD_UP 2L
#undef com_stokesautomation_gpio_rpi_RPiGpio_LOW
#define com_stokesautomation_gpio_rpi_RPiGpio_LOW 0L
#undef com_stokesautomation_gpio_rpi_RPiGpio_HIGH
#define com_stokesautomation_gpio_rpi_RPiGpio_HIGH 1L
#undef com_stokesautomation_gpio_rpi_RPiGpio_SETUP_OK
#define com_stokesautomation_gpio_rpi_RPiGpio_SETUP_OK 0L
#undef com_stokesautomation_gpio_rpi_RPiGpio_SETUP_DEVMEM_FAIL
#define com_stokesautomation_gpio_rpi_RPiGpio_SETUP_DEVMEM_FAIL 1L
#undef com_stokesautomation_gpio_rpi_RPiGpio_SETUP_MALLOC_FAIL
#define com_stokesautomation_gpio_rpi_RPiGpio_SETUP_MALLOC_FAIL 2L
#undef com_stokesautomation_gpio_rpi_RPiGpio_SETUP_MMAP_FAIL
#define com_stokesautomation_gpio_rpi_RPiGpio_SETUP_MMAP_FAIL 3L
#undef com_stokesautomation_gpio_rpi_RPiGpio_SETUP_CPUINFO_FAIL
#define com_stokesautomation_gpio_rpi_RPiGpio_SETUP_CPUINFO_FAIL 4L
#undef com_stokesautomation_gpio_rpi_RPiGpio_SETUP_NOT_RPI_FAIL
#define com_stokesautomation_gpio_rpi_RPiGpio_SETUP_NOT_RPI_FAIL 5L
/*
 * Class:     com_stokesautomation_gpio_rpi_RPiGpio
 * Method:    setup
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_stokesautomation_gpio_rpi_RPiGpio_setup
  (JNIEnv *, jobject);

/*
 * Class:     com_stokesautomation_gpio_rpi_RPiGpio
 * Method:    setup_gpio
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_com_stokesautomation_gpio_rpi_RPiGpio_setup_1gpio
  (JNIEnv *, jobject, jint, jint, jint);

/*
 * Class:     com_stokesautomation_gpio_rpi_RPiGpio
 * Method:    gpio_function
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_stokesautomation_gpio_rpi_RPiGpio_gpio_1function
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_stokesautomation_gpio_rpi_RPiGpio
 * Method:    output_gpio
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_stokesautomation_gpio_rpi_RPiGpio_output_1gpio
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_stokesautomation_gpio_rpi_RPiGpio
 * Method:    input_gpio
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_stokesautomation_gpio_rpi_RPiGpio_input_1gpio
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_stokesautomation_gpio_rpi_RPiGpio
 * Method:    set_rising_event
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_stokesautomation_gpio_rpi_RPiGpio_set_1rising_1event
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_stokesautomation_gpio_rpi_RPiGpio
 * Method:    set_falling_event
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_stokesautomation_gpio_rpi_RPiGpio_set_1falling_1event
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_stokesautomation_gpio_rpi_RPiGpio
 * Method:    set_high_event
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_stokesautomation_gpio_rpi_RPiGpio_set_1high_1event
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_stokesautomation_gpio_rpi_RPiGpio
 * Method:    set_low_event
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_stokesautomation_gpio_rpi_RPiGpio_set_1low_1event
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_stokesautomation_gpio_rpi_RPiGpio
 * Method:    eventdetected
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_stokesautomation_gpio_rpi_RPiGpio_eventdetected
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_stokesautomation_gpio_rpi_RPiGpio
 * Method:    cleanup
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_stokesautomation_gpio_rpi_RPiGpio_cleanup
  (JNIEnv *, jobject);

/*
 * Class:     com_stokesautomation_gpio_rpi_RPiGpio
 * Method:    getVersion
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_stokesautomation_gpio_rpi_RPiGpio_getVersion
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
